name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Tools/Deps
      run: |
        make install-tools
        make go-vendor

    - name: Lint
      run: make lint

    - name: Build
      run: make build
